// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoComSenhaApi.Data;

namespace ProjetoComSenhaApi.Migrations
{
    [DbContext(typeof(ProjetoComSenhaApiContext))]
    [Migration("20200611234857_InclusaoClasseRegiao")]
    partial class InclusaoClasseRegiao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProjetoComSenhaApi.Models.Partida", b =>
                {
                    b.Property<int>("PartidaId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CoJog1");

                    b.Property<int>("CoJog2");

                    b.Property<int>("CoTpJogo");

                    b.Property<string>("Nome");

                    b.HasKey("PartidaId");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("ProjetoComSenhaApi.Models.Regiao", b =>
                {
                    b.Property<int>("RegiaoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao");

                    b.HasKey("RegiaoId");

                    b.ToTable("Regiao");
                });
#pragma warning restore 612, 618
        }
    }
}
