//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace application.webservice_connection {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="serviceSoap", Namespace="http://tempuri.org/")]
    public partial class service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcessaJogosOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcessaJogosComParametroOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportaPedidoClienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public service() {
            this.Url = global::application.Properties.Settings.Default.application_webservice_connection_service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event AcessaJogosCompletedEventHandler AcessaJogosCompleted;
        
        /// <remarks/>
        public event AcessaJogosComParametroCompletedEventHandler AcessaJogosComParametroCompleted;
        
        /// <remarks/>
        public event ImportaPedidoClienteCompletedEventHandler ImportaPedidoClienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AcessaJogos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaJogosModelView AcessaJogos() {
            object[] results = this.Invoke("AcessaJogos", new object[0]);
            return ((ListaJogosModelView)(results[0]));
        }
        
        /// <remarks/>
        public void AcessaJogosAsync() {
            this.AcessaJogosAsync(null);
        }
        
        /// <remarks/>
        public void AcessaJogosAsync(object userState) {
            if ((this.AcessaJogosOperationCompleted == null)) {
                this.AcessaJogosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcessaJogosOperationCompleted);
            }
            this.InvokeAsync("AcessaJogos", new object[0], this.AcessaJogosOperationCompleted, userState);
        }
        
        private void OnAcessaJogosOperationCompleted(object arg) {
            if ((this.AcessaJogosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcessaJogosCompleted(this, new AcessaJogosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AcessaJogosComParametro", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaJogosModelView AcessaJogosComParametro() {
            object[] results = this.Invoke("AcessaJogosComParametro", new object[0]);
            return ((ListaJogosModelView)(results[0]));
        }
        
        /// <remarks/>
        public void AcessaJogosComParametroAsync() {
            this.AcessaJogosComParametroAsync(null);
        }
        
        /// <remarks/>
        public void AcessaJogosComParametroAsync(object userState) {
            if ((this.AcessaJogosComParametroOperationCompleted == null)) {
                this.AcessaJogosComParametroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcessaJogosComParametroOperationCompleted);
            }
            this.InvokeAsync("AcessaJogosComParametro", new object[0], this.AcessaJogosComParametroOperationCompleted, userState);
        }
        
        private void OnAcessaJogosComParametroOperationCompleted(object arg) {
            if ((this.AcessaJogosComParametroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcessaJogosComParametroCompleted(this, new AcessaJogosComParametroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportaPedidoCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PRetornoCliente ImportaPedidoCliente(ImportaPedido importaPedido) {
            object[] results = this.Invoke("ImportaPedidoCliente", new object[] {
                        importaPedido});
            return ((PRetornoCliente)(results[0]));
        }
        
        /// <remarks/>
        public void ImportaPedidoClienteAsync(ImportaPedido importaPedido) {
            this.ImportaPedidoClienteAsync(importaPedido, null);
        }
        
        /// <remarks/>
        public void ImportaPedidoClienteAsync(ImportaPedido importaPedido, object userState) {
            if ((this.ImportaPedidoClienteOperationCompleted == null)) {
                this.ImportaPedidoClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportaPedidoClienteOperationCompleted);
            }
            this.InvokeAsync("ImportaPedidoCliente", new object[] {
                        importaPedido}, this.ImportaPedidoClienteOperationCompleted, userState);
        }
        
        private void OnImportaPedidoClienteOperationCompleted(object arg) {
            if ((this.ImportaPedidoClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportaPedidoClienteCompleted(this, new ImportaPedidoClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaJogosModelView {
        
        private JogoModelView[] jogoModelViewField;
        
        private string noJogoField;
        
        private string dsJogoField;
        
        private int tipoJogoIdField;
        
        private double jogadoresRegistradosField;
        
        private double jogadoresOnlineField;
        
        private string codigoPromocionalField;
        
        private System.Nullable<System.DateTime> dtInicialField;
        
        private System.Nullable<System.DateTime> dtFinalField;
        
        /// <remarks/>
        public JogoModelView[] JogoModelView {
            get {
                return this.jogoModelViewField;
            }
            set {
                this.jogoModelViewField = value;
            }
        }
        
        /// <remarks/>
        public string NoJogo {
            get {
                return this.noJogoField;
            }
            set {
                this.noJogoField = value;
            }
        }
        
        /// <remarks/>
        public string DsJogo {
            get {
                return this.dsJogoField;
            }
            set {
                this.dsJogoField = value;
            }
        }
        
        /// <remarks/>
        public int TipoJogoId {
            get {
                return this.tipoJogoIdField;
            }
            set {
                this.tipoJogoIdField = value;
            }
        }
        
        /// <remarks/>
        public double JogadoresRegistrados {
            get {
                return this.jogadoresRegistradosField;
            }
            set {
                this.jogadoresRegistradosField = value;
            }
        }
        
        /// <remarks/>
        public double JogadoresOnline {
            get {
                return this.jogadoresOnlineField;
            }
            set {
                this.jogadoresOnlineField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoPromocional {
            get {
                return this.codigoPromocionalField;
            }
            set {
                this.codigoPromocionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DtInicial {
            get {
                return this.dtInicialField;
            }
            set {
                this.dtInicialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DtFinal {
            get {
                return this.dtFinalField;
            }
            set {
                this.dtFinalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class JogoModelView {
        
        private int jogoModelViewIdField;
        
        private string noJogoField;
        
        private string dsJogoField;
        
        private int tipoJogoIdField;
        
        private double jogadoresRegistradosField;
        
        private double jogadoresOnlineField;
        
        private string codigoPromocionalField;
        
        /// <remarks/>
        public int JogoModelViewId {
            get {
                return this.jogoModelViewIdField;
            }
            set {
                this.jogoModelViewIdField = value;
            }
        }
        
        /// <remarks/>
        public string NoJogo {
            get {
                return this.noJogoField;
            }
            set {
                this.noJogoField = value;
            }
        }
        
        /// <remarks/>
        public string DsJogo {
            get {
                return this.dsJogoField;
            }
            set {
                this.dsJogoField = value;
            }
        }
        
        /// <remarks/>
        public int TipoJogoId {
            get {
                return this.tipoJogoIdField;
            }
            set {
                this.tipoJogoIdField = value;
            }
        }
        
        /// <remarks/>
        public double JogadoresRegistrados {
            get {
                return this.jogadoresRegistradosField;
            }
            set {
                this.jogadoresRegistradosField = value;
            }
        }
        
        /// <remarks/>
        public double JogadoresOnline {
            get {
                return this.jogadoresOnlineField;
            }
            set {
                this.jogadoresOnlineField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoPromocional {
            get {
                return this.codigoPromocionalField;
            }
            set {
                this.codigoPromocionalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RetornoLab {
        
        private string pedidoField;
        
        private string ordemServicoField;
        
        private Exame[] examesField;
        
        private bool retornoField;
        
        private string descErroField;
        
        /// <remarks/>
        public string Pedido {
            get {
                return this.pedidoField;
            }
            set {
                this.pedidoField = value;
            }
        }
        
        /// <remarks/>
        public string OrdemServico {
            get {
                return this.ordemServicoField;
            }
            set {
                this.ordemServicoField = value;
            }
        }
        
        /// <remarks/>
        public Exame[] Exames {
            get {
                return this.examesField;
            }
            set {
                this.examesField = value;
            }
        }
        
        /// <remarks/>
        public bool Retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        public string DescErro {
            get {
                return this.descErroField;
            }
            set {
                this.descErroField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Exame {
        
        private string codigoField;
        
        private string codigoApoioField;
        
        private string codigoLISOrigemField;
        
        private string sequencialComplementarField;
        
        private string descricaoField;
        
        private InformacaoPreAnalitica[] informacoesPreAnaliticasField;
        
        private Amostra[] amostrasField;
        
        private string descMaterialField;
        
        private Medico[] medicosField;
        
        private string urgenteField;
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoApoio {
            get {
                return this.codigoApoioField;
            }
            set {
                this.codigoApoioField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoLISOrigem {
            get {
                return this.codigoLISOrigemField;
            }
            set {
                this.codigoLISOrigemField = value;
            }
        }
        
        /// <remarks/>
        public string SequencialComplementar {
            get {
                return this.sequencialComplementarField;
            }
            set {
                this.sequencialComplementarField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public InformacaoPreAnalitica[] InformacoesPreAnaliticas {
            get {
                return this.informacoesPreAnaliticasField;
            }
            set {
                this.informacoesPreAnaliticasField = value;
            }
        }
        
        /// <remarks/>
        public Amostra[] Amostras {
            get {
                return this.amostrasField;
            }
            set {
                this.amostrasField = value;
            }
        }
        
        /// <remarks/>
        public string DescMaterial {
            get {
                return this.descMaterialField;
            }
            set {
                this.descMaterialField = value;
            }
        }
        
        /// <remarks/>
        public Medico[] Medicos {
            get {
                return this.medicosField;
            }
            set {
                this.medicosField = value;
            }
        }
        
        /// <remarks/>
        public string Urgente {
            get {
                return this.urgenteField;
            }
            set {
                this.urgenteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InformacaoPreAnalitica {
        
        private string identificadorField;
        
        private string valorField;
        
        /// <remarks/>
        public string Identificador {
            get {
                return this.identificadorField;
            }
            set {
                this.identificadorField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Amostra {
        
        private string codigoBarraField;
        
        private string recipienteField;
        
        private string etiquetaField;
        
        /// <remarks/>
        public string CodigoBarra {
            get {
                return this.codigoBarraField;
            }
            set {
                this.codigoBarraField = value;
            }
        }
        
        /// <remarks/>
        public string Recipiente {
            get {
                return this.recipienteField;
            }
            set {
                this.recipienteField = value;
            }
        }
        
        /// <remarks/>
        public string Etiqueta {
            get {
                return this.etiquetaField;
            }
            set {
                this.etiquetaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Medico {
        
        private string nomeField;
        
        private string crmField;
        
        private string conselhoField;
        
        private string ufField;
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Crm {
            get {
                return this.crmField;
            }
            set {
                this.crmField = value;
            }
        }
        
        /// <remarks/>
        public string Conselho {
            get {
                return this.conselhoField;
            }
            set {
                this.conselhoField = value;
            }
        }
        
        /// <remarks/>
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaRetornoLab {
        
        private RetornoLab[] retornoLabField;
        
        /// <remarks/>
        public RetornoLab[] RetornoLab {
            get {
                return this.retornoLabField;
            }
            set {
                this.retornoLabField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PRetornoCliente {
        
        private ListaRetornoLab listaRetornoLabField;
        
        /// <remarks/>
        public ListaRetornoLab ListaRetornoLab {
            get {
                return this.listaRetornoLabField;
            }
            set {
                this.listaRetornoLabField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Endereco {
        
        private string logradouroField;
        
        private string complementoField;
        
        private string numeroField;
        
        private string bairroField;
        
        private string cepField;
        
        private string cidadeField;
        
        private string estadoField;
        
        private string tipoField;
        
        /// <remarks/>
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Paciente {
        
        private string usuarioWebField;
        
        private string senhaWebField;
        
        private string codigoField;
        
        private string nomeField;
        
        private string sexoField;
        
        private string dtNascimentoField;
        
        private string alturaField;
        
        private string pesoField;
        
        private string dumField;
        
        private string rgField;
        
        private string cpfField;
        
        private string cnsField;
        
        private string emailField;
        
        private string telefoneField;
        
        private string celularField;
        
        private string medicamentoField;
        
        private Endereco[] enderecosField;
        
        private string anamneseField;
        
        /// <remarks/>
        public string UsuarioWeb {
            get {
                return this.usuarioWebField;
            }
            set {
                this.usuarioWebField = value;
            }
        }
        
        /// <remarks/>
        public string SenhaWeb {
            get {
                return this.senhaWebField;
            }
            set {
                this.senhaWebField = value;
            }
        }
        
        /// <remarks/>
        public string Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public string DtNascimento {
            get {
                return this.dtNascimentoField;
            }
            set {
                this.dtNascimentoField = value;
            }
        }
        
        /// <remarks/>
        public string Altura {
            get {
                return this.alturaField;
            }
            set {
                this.alturaField = value;
            }
        }
        
        /// <remarks/>
        public string Peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
            }
        }
        
        /// <remarks/>
        public string Dum {
            get {
                return this.dumField;
            }
            set {
                this.dumField = value;
            }
        }
        
        /// <remarks/>
        public string Rg {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        public string Cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string Cns {
            get {
                return this.cnsField;
            }
            set {
                this.cnsField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Celular {
            get {
                return this.celularField;
            }
            set {
                this.celularField = value;
            }
        }
        
        /// <remarks/>
        public string Medicamento {
            get {
                return this.medicamentoField;
            }
            set {
                this.medicamentoField = value;
            }
        }
        
        /// <remarks/>
        public Endereco[] Enderecos {
            get {
                return this.enderecosField;
            }
            set {
                this.enderecosField = value;
            }
        }
        
        /// <remarks/>
        public string Anamnese {
            get {
                return this.anamneseField;
            }
            set {
                this.anamneseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pedido {
        
        private string ordemServicoField;
        
        private string observacaoField;
        
        /// <remarks/>
        public string OrdemServico {
            get {
                return this.ordemServicoField;
            }
            set {
                this.ordemServicoField = value;
            }
        }
        
        /// <remarks/>
        public string Observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PedidoLab {
        
        private Pedido pedidoField;
        
        private Paciente pacienteField;
        
        private Exame[] examesField;
        
        /// <remarks/>
        public Pedido Pedido {
            get {
                return this.pedidoField;
            }
            set {
                this.pedidoField = value;
            }
        }
        
        /// <remarks/>
        public Paciente Paciente {
            get {
                return this.pacienteField;
            }
            set {
                this.pacienteField = value;
            }
        }
        
        /// <remarks/>
        public Exame[] Exames {
            get {
                return this.examesField;
            }
            set {
                this.examesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ImportaPedido {
        
        private string idLaboratorioField;
        
        private string senhaField;
        
        private PedidoLab[] listaPedidoLabField;
        
        /// <remarks/>
        public string IdLaboratorio {
            get {
                return this.idLaboratorioField;
            }
            set {
                this.idLaboratorioField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public PedidoLab[] ListaPedidoLab {
            get {
                return this.listaPedidoLabField;
            }
            set {
                this.listaPedidoLabField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AcessaJogosCompletedEventHandler(object sender, AcessaJogosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AcessaJogosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AcessaJogosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaJogosModelView Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaJogosModelView)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AcessaJogosComParametroCompletedEventHandler(object sender, AcessaJogosComParametroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AcessaJogosComParametroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AcessaJogosComParametroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaJogosModelView Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaJogosModelView)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ImportaPedidoClienteCompletedEventHandler(object sender, ImportaPedidoClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportaPedidoClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportaPedidoClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public PRetornoCliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PRetornoCliente)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591