//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace cliente.service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="serviceSoap", Namespace="http://tempuri.org/")]
    public partial class service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback AcessaJogosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public service() {
            this.Url = global::cliente.Properties.Settings.Default.cliente_service_service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event AcessaJogosCompletedEventHandler AcessaJogosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AcessaJogos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ListaJogosModelView AcessaJogos() {
            object[] results = this.Invoke("AcessaJogos", new object[0]);
            return ((ListaJogosModelView)(results[0]));
        }
        
        /// <remarks/>
        public void AcessaJogosAsync() {
            this.AcessaJogosAsync(null);
        }
        
        /// <remarks/>
        public void AcessaJogosAsync(object userState) {
            if ((this.AcessaJogosOperationCompleted == null)) {
                this.AcessaJogosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAcessaJogosOperationCompleted);
            }
            this.InvokeAsync("AcessaJogos", new object[0], this.AcessaJogosOperationCompleted, userState);
        }
        
        private void OnAcessaJogosOperationCompleted(object arg) {
            if ((this.AcessaJogosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AcessaJogosCompleted(this, new AcessaJogosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ListaJogosModelView {
        
        private JogoModelView[] jogoModelViewField;
        
        private string noJogoField;
        
        private string dsJogoField;
        
        private int tipoJogoIdField;
        
        private double jogadoresRegistradosField;
        
        private double jogadoresOnlineField;
        
        private string codigoPromocionalField;
        
        private System.Nullable<System.DateTime> dtInicialField;
        
        private System.Nullable<System.DateTime> dtFinalField;
        
        /// <remarks/>
        public JogoModelView[] JogoModelView {
            get {
                return this.jogoModelViewField;
            }
            set {
                this.jogoModelViewField = value;
            }
        }
        
        /// <remarks/>
        public string NoJogo {
            get {
                return this.noJogoField;
            }
            set {
                this.noJogoField = value;
            }
        }
        
        /// <remarks/>
        public string DsJogo {
            get {
                return this.dsJogoField;
            }
            set {
                this.dsJogoField = value;
            }
        }
        
        /// <remarks/>
        public int TipoJogoId {
            get {
                return this.tipoJogoIdField;
            }
            set {
                this.tipoJogoIdField = value;
            }
        }
        
        /// <remarks/>
        public double JogadoresRegistrados {
            get {
                return this.jogadoresRegistradosField;
            }
            set {
                this.jogadoresRegistradosField = value;
            }
        }
        
        /// <remarks/>
        public double JogadoresOnline {
            get {
                return this.jogadoresOnlineField;
            }
            set {
                this.jogadoresOnlineField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoPromocional {
            get {
                return this.codigoPromocionalField;
            }
            set {
                this.codigoPromocionalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DtInicial {
            get {
                return this.dtInicialField;
            }
            set {
                this.dtInicialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DtFinal {
            get {
                return this.dtFinalField;
            }
            set {
                this.dtFinalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class JogoModelView {
        
        private int jogoModelViewIdField;
        
        private string noJogoField;
        
        private string dsJogoField;
        
        private int tipoJogoIdField;
        
        private double jogadoresRegistradosField;
        
        private double jogadoresOnlineField;
        
        private string codigoPromocionalField;
        
        /// <remarks/>
        public int JogoModelViewId {
            get {
                return this.jogoModelViewIdField;
            }
            set {
                this.jogoModelViewIdField = value;
            }
        }
        
        /// <remarks/>
        public string NoJogo {
            get {
                return this.noJogoField;
            }
            set {
                this.noJogoField = value;
            }
        }
        
        /// <remarks/>
        public string DsJogo {
            get {
                return this.dsJogoField;
            }
            set {
                this.dsJogoField = value;
            }
        }
        
        /// <remarks/>
        public int TipoJogoId {
            get {
                return this.tipoJogoIdField;
            }
            set {
                this.tipoJogoIdField = value;
            }
        }
        
        /// <remarks/>
        public double JogadoresRegistrados {
            get {
                return this.jogadoresRegistradosField;
            }
            set {
                this.jogadoresRegistradosField = value;
            }
        }
        
        /// <remarks/>
        public double JogadoresOnline {
            get {
                return this.jogadoresOnlineField;
            }
            set {
                this.jogadoresOnlineField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoPromocional {
            get {
                return this.codigoPromocionalField;
            }
            set {
                this.codigoPromocionalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AcessaJogosCompletedEventHandler(object sender, AcessaJogosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AcessaJogosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AcessaJogosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ListaJogosModelView Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ListaJogosModelView)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591